# Default values for nbexchange.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/noteable/nbexchange
  tag: latest
  pullPolicy: IfNotPresent

environment:
  NBEX_DB_URL: ""
  SENTRY_DSN: ""
  DEBUG: "0"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9000

ingress:
  enable: true
  url: nbexchange.cluster-dev.example.com

resources:
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

paths:
  service_prefix: /services/nbexchange/
  base_store: /tmp/courses
