variables:
#  TWINE_USERNAME: SECURE
#  TWINE_PASSWORD: SECURE
#  TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

stages:
  - lint
  - test
# - deploy

#deploy:
#  image: python:3.6
#  stage: deploy
#  script:
#    - pip install -U twine setuptools
#    - pip list
#    - python setup.py sdist bdist_wheel
#    - twine upload dist/*.tar.gz
#    - twine upload dist/*.whl
#  only:
#    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)]
lint:
  image: python:3.6
  stage: lint
  script:
    - pip install black
    - black --check nbexchange

test:
  image: python:3.6
  stage: test
  script:
    - python setup.py test