variables:
  VERSION: $CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG

image: registry.gitlab.edina.ac.uk:1875/shared/gitlab-ci-tools

stages:
  - build
  - publish

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose build
    - docker tag edina/nbexchange:$VERSION $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:$VERSION

publish-python:
  stage: publish
  variables:
    FLIT_INDEX_URL: https://gitlab.edina.ac.uk/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
  script:
    - pip install flit
    - flit build
    - FLIT_PASSWORD=${CI_JOB_TOKEN} FLIT_USERNAME=gitlab-ci-token flit publish
