# This file is specific to the EDINA in-house gitlab repo... where we internally
# build & distribute our instance of the service
include:
  - project: "naas/Group-issues"
    file: "/common-templates.yml"

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE # Needs to match production.yml
  LOCATION: "."

stages:
  - build
  - release-branch
  - release-master
  - delete


# master branch builds CI-SLUG & latest
build-app:
  extends: .build-template

# working branch only builds C_-SLUG
release-branch:
  extends: .release-branch-template

release-master:
  extends: .release-master-template

delete-image:
  extends: .delete-template

