variables:
  VERSION: $CI_PIPELINE_ID-$CI_COMMIT_REF_SLUG

image: registry.gitlab.edina.ac.uk:1875/shared/gitlab-ci-tools

stages:
  - build

build:
  stage: build
  script:
    - docker-compose build
    - docker tag edina/nbexchange:$VERSION $CI_REGISTRY:$VERSION
    - docker push $CI_REGISTRY:$VERSION
