apiVersion: v1
kind: ConfigMap
metadata:
  name: nbexchange-config
data:
{{- if or $.Values.environment }}
  {{- range $key, $value := $.Values.environment }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}