apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nbexchange.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nbexchange.name" . }}
    helm.sh/chart: {{ include "nbexchange.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nbexchange.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nbexchange.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /services/nbexchange/
              port: http
          readinessProbe:
            httpGet:
              path: /services/nbexchange/
              port: http
          volumeMounts:
            - mountPath: /disk/remote/courses/
              name: courses
          envFrom:
          - configMapRef:
              name: nbexchange-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: courses
        hostPath:
          path: /disk/remote/courses/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
