"""Change feedback timestamp column type to DateTime

Revision ID: 2805bf7747e5
Revises: f26d6a79159d
Create Date: 2020-06-23 13:58:38.781382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2805bf7747e5"
down_revision = "f26d6a79159d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
