# Technically covered by pre-commit - but here as a "double-check" catcher.

name: Linted

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: pip install .
    - name: Lint with black
      run: |
        pip install black
        # stop the build if it's not linted as per black
        black --check --diff nbexchange/
